name: Update README every 12 hours

on:
  push:
  schedule:
    # “At 13:37 on every day-of-week from Monday through Friday.”
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:


# This is the DYNAMIC name for each individual run.
run-name: "Update README triggered by ${{ github.event_name }} (Run #${{ github.run_number }})"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update README at ${{ github.run_attempt }}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node index.js > README.md
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: younes-ammari
          author_email: dev.younes.ammari@gmail.com
          force: false
          signoff: false
          message: ':memo: README.md updated by Gabot'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
